"""new adjustments

Revision ID: 054521ec95dc
Revises: ba852051d9ce
Create Date: 2024-09-03 00:00:54.322503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '054521ec95dc'
down_revision: Union[str, None] = 'ba852051d9ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('password', sa.String(), nullable=False))
    op.drop_column('companies', 'hashed_password')
    op.add_column('super_admins', sa.Column('password', sa.String(), nullable=False))
    op.drop_column('super_admins', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('super_admins', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('super_admins', 'password')
    op.add_column('companies', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('companies', 'password')
    # ### end Alembic commands ###
