"""modified AssetAssign model

Revision ID: 47c3bcd2207e
Revises: ce0265b3adea
Create Date: 2024-08-31 23:14:00.298152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47c3bcd2207e'
down_revision: Union[str, None] = 'ce0265b3adea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_assignments', sa.Column('is_assigned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_assignments', 'is_assigned')
    # ### end Alembic commands ###
