"""modified some tables

Revision ID: ba852051d9ce
Revises: c579a8511808
Create Date: 2024-09-02 20:29:48.744641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba852051d9ce'
down_revision: Union[str, None] = 'c579a8511808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_column('companies', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('companies', 'hashed_password')
    # ### end Alembic commands ###
