"""Add CompanyPending table

Revision ID: cb65c59fa520
Revises: 2f6f49687e3e
Create Date: 2024-09-06 19:03:49.530018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb65c59fa520'
down_revision: Union[str, None] = '2f6f49687e3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies_pending', sa.Column('address', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies_pending', 'address')
    # ### end Alembic commands ###
