"""modified some table

Revision ID: ce0265b3adea
Revises: fcddd3171fb4
Create Date: 2024-08-31 22:07:14.761295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce0265b3adea'
down_revision: Union[str, None] = 'fcddd3171fb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_assignments', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_assignments', 'created_at')
    # ### end Alembic commands ###
